/**
 * Thin LLM client abstraction.
 *
 * Swap the provider via the LLM_PROVIDER env var:
 *   mock     — deterministic fake response (default, no API key needed)
 *   openai   — calls OpenAI chat completions
 *   anthropic — calls Anthropic messages API
 */

export interface LLMRequest {
  systemPrompt: string;
  userMessage: string;
}

export interface LLMResponse {
  content: string;
}

export async function callLLM(req: LLMRequest): Promise<LLMResponse> {
  const provider = process.env.LLM_PROVIDER ?? "mock";

  switch (provider) {
    case "openai":
      return callOpenAI(req);
    case "anthropic":
      return callAnthropic(req);
    case "mock":
    default:
      return callMock(req);
  }
}

// ---------------------------------------------------------------------------
// Mock provider — returns deterministic JSON for development / tests
// ---------------------------------------------------------------------------

function callMock(req: LLMRequest): LLMResponse {
  // Detect which kind of output is expected from the system prompt keywords.
  const isTower = req.systemPrompt.toLowerCase().includes("tower");
  const isWave = req.systemPrompt.toLowerCase().includes("wave");

  if (isTower) {
    return {
      content: JSON.stringify({
        name: "Mock Turret",
        damage: 50,
        range: 200,
        fireRate: 1.5,
        cost: 100,
        effect: "none",
        description: "A placeholder tower generated by the mock LLM provider.",
      }),
    };
  }

  if (isWave) {
    return {
      content: JSON.stringify({
        waveNumber: 1,
        groups: [
          {
            enemy: {
              name: "Mock Grunt",
              hp: 80,
              speed: 60,
              reward: 10,
              damage: 5,
              description: "A placeholder enemy generated by the mock LLM provider.",
            },
            count: 10,
            spawnInterval: 1,
          },
        ],
      }),
    };
  }

  return { content: "{}" };
}

// ---------------------------------------------------------------------------
// OpenAI provider
// ---------------------------------------------------------------------------

async function callOpenAI(req: LLMRequest): Promise<LLMResponse> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) throw new Error("OPENAI_API_KEY is not set");

  const model = process.env.OPENAI_MODEL ?? "gpt-4o";

  const response = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: req.systemPrompt },
        { role: "user", content: req.userMessage },
      ],
    }),
  });

  if (!response.ok) {
    throw new Error(`OpenAI API error: ${response.status} ${response.statusText}`);
  }

  const data = (await response.json()) as {
    choices: Array<{ message: { content: string } }>;
  };

  return { content: data.choices[0].message.content };
}

// ---------------------------------------------------------------------------
// Anthropic provider
// ---------------------------------------------------------------------------

async function callAnthropic(req: LLMRequest): Promise<LLMResponse> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error("ANTHROPIC_API_KEY is not set");

  const model = process.env.ANTHROPIC_MODEL ?? "claude-3-5-sonnet-20241022";

  const response = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model,
      max_tokens: 1024,
      system: req.systemPrompt,
      messages: [{ role: "user", content: req.userMessage }],
    }),
  });

  if (!response.ok) {
    throw new Error(`Anthropic API error: ${response.status} ${response.statusText}`);
  }

  const data = (await response.json()) as {
    content: Array<{ type: string; text: string }>;
  };

  const textBlock = data.content.find((b) => b.type === "text");
  if (!textBlock) throw new Error("No text block in Anthropic response");

  return { content: textBlock.text };
}
